Repository kyverno/website, pull requests merged in 2021-08, with the labels that each got.

#196 customizable Helm release name
  content/en/docs/Installation/_index.md
Labels: hold

#249 Fix typo in cosign tutorial.
  content/en/docs/Writing policies/verify-images.md
  content/en/policies/other/verify_image.md
Labels: bug, documentation

#247 [1.4.1] fixes, updates; policy rendering
  content/en/docs/Installation/_index.md
  content/en/docs/Policy Reports/_index.md
  content/en/docs/Writing policies/match-exclude.md
  content/en/policies/best-practices/check_deprecated_apis.md
  content/en/policies/best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.md
  content/en/policies/best-practices/disallow_default_namespace/disallow_default_namespace.md
  content/en/policies/best-practices/require_pod_requests_limits/require_pod_requests_limits.md
  content/en/policies/cert-manager/limit-dnsnames.md
  content/en/policies/other/add-imagepullsecrets.md
  content/en/policies/other/add_nodeSelector.md
  content/en/policies/other/block-pod-exec-by-namespace-label.md
  content/en/policies/other/block-pod-exec-by-namespace.md
  content/en/policies/other/block-pod-exec-by-pod-and-container.md
  content/en/policies/other/block-pod-exec-by-pod-label.md
  content/en/policies/other/block-pod-exec-by-pod-name.md
  content/en/policies/other/pod_lifetime_annotation/enforce_pod_duration.md
  content/en/policies/other/restrict_usergroup_fsgroup_id.md
  content/en/policies/other/spread_pods_across_topology.md
  content/en/policies/other/verify_image.md
Labels: bug

#246 [main] README updates; remove reference to Kyverno CM; render policies
  README.md
  content/en/docs/Installation/_index.md
  content/en/docs/Policy Reports/_index.md
  content/en/policies/best-practices/check_deprecated_apis.md
  content/en/policies/best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.md
  content/en/policies/best-practices/disallow_default_namespace/disallow_default_namespace.md
  content/en/policies/best-practices/require_pod_requests_limits/require_pod_requests_limits.md
  content/en/policies/cert-manager/limit-dnsnames.md
  content/en/policies/other/add-imagepullsecrets.md
  content/en/policies/other/add_nodeSelector.md
  content/en/policies/other/block-pod-exec-by-namespace-label.md
  content/en/policies/other/block-pod-exec-by-namespace.md
  content/en/policies/other/block-pod-exec-by-pod-and-container.md
  content/en/policies/other/block-pod-exec-by-pod-label.md
  content/en/policies/other/block-pod-exec-by-pod-name.md
  content/en/policies/other/pod_lifetime_annotation/enforce_pod_duration.md
  content/en/policies/other/restrict_usergroup_fsgroup_id.md
  content/en/policies/other/spread_pods_across_topology.md
  render/README.md
Labels: internal

#261 [1.4.2] Update 1.4.2 with latest changes from main
  content/en/_index.html
  content/en/docs/Installation/_index.md
Labels: documentation
