Repository kyverno/website, pull requests merged in 2021-12, with the labels that each got.

#351 [1.5.2] Added docs for resource quantity comparison
  content/en/docs/Writing policies/preconditions.md
Labels: hold

#317 [1.5.0] Updated doc for flags
  content/en/docs/Installation/_index.md
Labels: question, hold

#411 Updates for v1.5.2
  .gitignore
  content/en/docs/Releases/_index.md
  content/en/docs/Writing policies/mutate.md
  content/en/policies/cert-manager/limit-duration/limit-duration.md
  content/en/policies/other/add_node_affinity/add_node_affinity.md
  content/en/policies/other/allowed_pod_priorities/allowed_pod_priorities.md
  content/en/policies/other/disable_automountserviceaccounttoken/disable-automountserviceaccounttoken.md
  content/en/policies/other/disallow_all_secrets/disallow_all_secrets.md
  content/en/policies/other/exclude_namespaces_dynamically.md
  content/en/policies/other/pod_lifetime_annotation/enforce_pod_duration.md
  content/en/policies/other/prepend_image_registry/prepend_image_registry.md
  content/en/policies/other/protect_node_taints/protect-node-taints.md
  content/en/policies/other/require_unique_external_dns/require_unique_external_dns.md
  content/en/policies/other/require_unique_uid_per_workload/require_unique_uid_per_workload.md
  content/en/policies/traefik/disallow_default_tlsoptions/disallow_default_tlsoptions.md
Labels: documentation

#413 Updates for v1.5.2
  .gitignore
  content/en/docs/Installation/_index.md
  content/en/docs/Kyverno CLI/_index.md
  content/en/docs/Monitoring Kyverno With Prometheus Metrics/_index.md
  content/en/docs/Monitoring Kyverno With Prometheus Metrics/policy-results-info.md
  content/en/docs/Releases/_index.md
  content/en/docs/Writing policies/mutate.md
  content/en/docs/Writing policies/preconditions.md
  content/en/docs/Writing policies/variables.md
  content/en/docs/_index.md
  content/en/policies/cert-manager/limit-duration/limit-duration.md
  content/en/policies/other/add_node_affinity/add_node_affinity.md
  content/en/policies/other/allowed_pod_priorities/allowed_pod_priorities.md
  content/en/policies/other/disable_automountserviceaccounttoken/disable-automountserviceaccounttoken.md
  content/en/policies/other/disallow_all_secrets/disallow_all_secrets.md
  content/en/policies/other/exclude_namespaces_dynamically.md
  content/en/policies/other/pod_lifetime_annotation/enforce_pod_duration.md
  content/en/policies/other/prepend_image_registry/prepend_image_registry.md
  content/en/policies/other/protect_node_taints/protect-node-taints.md
  content/en/policies/other/require_unique_external_dns/require_unique_external_dns.md
  content/en/policies/other/require_unique_uid_per_workload/require_unique_uid_per_workload.md
  content/en/policies/traefik/disallow_default_tlsoptions/disallow_default_tlsoptions.md
  content/en/resources/_index.md
  content/en/support/_index.md
  deploy.sh
  scripts/hash-files.sh
Labels: documentation

#415 Doc fixes
  content/en/docs/Installation/_index.md
  content/en/docs/Releases/_index.md
  content/en/docs/Writing policies/external-data-sources.md
  content/en/docs/Writing policies/generate.md
  content/en/docs/Writing policies/validate.md
  content/en/docs/Writing policies/variables.md
Labels: bug, documentation
