Repository kyverno/website, pull requests merged in 2022-01, with the labels that each got.

#435 Render policies; fixes
  README.md
  content/en/docs/Policy Reports/_index.md
  content/en/docs/Writing policies/background.md
  content/en/docs/Writing policies/mutate.md
  content/en/policies/best-practices/add_safe_to_evict.md
  content/en/policies/other/add-imagepullsecrets-for-containers-and-initcontainers.md
  content/en/policies/other/add_certificates_volume/add_certificates_volume.md
  content/en/policies/other/check_serviceaccount/check_serviceaccount.md
  content/en/policies/other/inject_sidecar_deployment/inject_sidecar_deployment.md
  content/en/policies/other/mitigate_log4shell/mitigate_log4shell.md
  content/en/policies/other/prepend_image_registry/prepend_image_registry.md
  content/en/policies/other/restrict_automount_sa_token/restrict_automount_sa_token.md
  content/en/policies/other/restrict_service_account.md
Labels: bug, documentation

#461 fixed auto-gen URL
  content/en/docs/Writing policies/verify-images.md
Labels: bug

#391 [1.6.0] Document `pattern_match` JMESPath custom function
  content/en/docs/Writing policies/variables.md
Labels: hold

#363 [1.6.0] *Range operators
  content/en/docs/Writing policies/validate.md
Labels: hold

#353 [1.6.0] Added doc for new operators
  content/en/docs/Writing policies/preconditions.md
Labels: hold
